apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-bus
spec:
  serviceName: event-bus
  selector:
    matchLabels:
      event-bus-service: event-bus
  template:
    metadata:
      labels:
        event-bus-service: event-bus
        system: event-bus
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: event-bus-data
        persistentVolumeClaim:
          claimName: event-bus-data
      containers:
      - name: event-bus
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: event-bus-password
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-user
        volumeMounts:
        - name: event-bus-data
          mountPath: /var/lib/rabbitmq/mnesia
